spring:
  application:
    name: orderms

server:
  port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#Actuator(Visualize the circuit-breaker state changes)
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: debug

#Circuitbreaker result for changing state
resilience4j:
  circuitbreaker:
    configs:
      defaults:
        slidingWindowSize: 8
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 30
        minimumNumberOfCalls: 4
    instances:
      usermsclient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransferFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 20
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3




